"""Built-in signature definitions seeded into PostgreSQL on first run.

Each entry maps to the DetectionRule model. Rules are stored in the
database and editable through the /rules API.
"""

BUILTIN_RULES = [
    {
        "rule_id": "RULE-AUTH-001",
        "name": "Multiple Failed Logons",
        "description": "More than 5 failed logons from the same source within 5 minutes.",
        "category": "authentication",
        "severity": "high",
        "event_id": [4625],
        "conditions": {"field": "source_ip"},
        "correlation_type": "count",
        "threshold": 5,
        "time_window_seconds": 300,
        "correlation_key": "source_ip",
        "mitre_technique": "T1110",
        "mitre_name": "Brute Force",
    },
    {
        "rule_id": "RULE-AUTH-002",
        "name": "Successful Logon After Multiple Failures",
        "description": "Multiple failed logons followed by a successful authentication.",
        "category": "authentication",
        "severity": "critical",
        "event_id": [4625, 4624],
        "conditions": {"sequence": [{"event_id": 4625}, {"event_id": 4624}], "window": 600},
        "correlation_type": "sequence",
        "threshold": 3,
        "time_window_seconds": 600,
        "correlation_key": "username",
        "mitre_technique": "T1110",
        "mitre_name": "Brute Force",
    },
    {
        "rule_id": "RULE-AUDIT-001",
        "name": "Security Audit Log Cleared",
        "description": "The Windows security event log was cleared.",
        "category": "security_audit",
        "severity": "critical",
        "event_id": [1102],
        "conditions": {},
        "correlation_type": "none",
        "threshold": 1,
        "time_window_seconds": 60,
        "correlation_key": None,
        "mitre_technique": "T1070.001",
        "mitre_name": "Clear Windows Event Logs",
    },
    {
        "rule_id": "RULE-SVC-001",
        "name": "New Service Installed",
        "description": "A new Windows service was installed on the host.",
        "category": "service_installation",
        "severity": "high",
        "event_id": [7045],
        "conditions": {},
        "correlation_type": "none",
        "threshold": 1,
        "time_window_seconds": 60,
        "correlation_key": None,
        "mitre_technique": "T1543.003",
        "mitre_name": "Windows Service",
    },
    {
        "rule_id": "RULE-ACCT-001",
        "name": "New User Account Created",
        "description": "A new local user account was created on a monitored host.",
        "category": "account_management",
        "severity": "high",
        "event_id": [4720],
        "conditions": {},
        "correlation_type": "none",
        "threshold": 1,
        "time_window_seconds": 60,
        "correlation_key": None,
        "mitre_technique": "T1136.001",
        "mitre_name": "Local Account",
    },
    {
        "rule_id": "RULE-ACCT-002",
        "name": "User Added to Privileged Group",
        "description": "A user account was added to a security-privileged group.",
        "category": "account_management",
        "severity": "high",
        "event_id": [4728, 4732],
        "conditions": {},
        "correlation_type": "none",
        "threshold": 1,
        "time_window_seconds": 60,
        "correlation_key": None,
        "mitre_technique": "T1098",
        "mitre_name": "Account Manipulation",
    },
    {
        "rule_id": "RULE-PRIV-001",
        "name": "Special Privileges Assigned",
        "description": "Special privileges (e.g. SeDebugPrivilege) were assigned to a logon.",
        "category": "privilege_assignment",
        "severity": "medium",
        "event_id": [4672],
        "conditions": {},
        "correlation_type": "none",
        "threshold": 1,
        "time_window_seconds": 60,
        "correlation_key": None,
        "mitre_technique": "T1134",
        "mitre_name": "Access Token Manipulation",
    },
    {
        "rule_id": "RULE-CRED-001",
        "name": "Explicit Credential Usage",
        "description": "A process logged on using explicit credentials (runas / scheduled task).",
        "category": "credential_usage",
        "severity": "medium",
        "event_id": [4648],
        "conditions": {},
        "correlation_type": "none",
        "threshold": 1,
        "time_window_seconds": 60,
        "correlation_key": None,
        "mitre_technique": "T1078",
        "mitre_name": "Valid Accounts",
    },
    {
        "rule_id": "RULE-PROC-001",
        "name": "Suspicious PowerShell Execution",
        "description": "PowerShell executed with encoded/hidden/download patterns.",
        "category": "process_creation",
        "severity": "high",
        "event_id": [4688],
        "conditions": {
            "command_line": {
                "contains_any": [
                    "-enc", "-encodedcommand", "-nop -w hidden", "-windowstyle hidden",
                    "invoke-webrequest", "downloadstring", "net.webclient",
                    "frombase64string", "iex(", "iwr ",
                ]
            }
        },
        "correlation_type": "none",
        "threshold": 1,
        "time_window_seconds": 60,
        "correlation_key": None,
        "mitre_technique": "T1059.001",
        "mitre_name": "PowerShell",
    },
    {
        "rule_id": "RULE-CRED-002",
        "name": "LSASS Process Access (Credential Dumping)",
        "description": "A process opened lsass.exe with a memory-read access mask (4663), consistent with credential dumping tools (mimikatz, procdump, comsvcs, rundll32, sqldumper).",
        "category": "credential_access",
        "severity": "high",
        "event_id": [4663],
        "conditions": {
            "process_name": {
                "contains_any": ["mimikatz", "procdump", "comsvcs", "rundll32", "sqldumper"]
            }
        },
        "correlation_type": "none",
        "threshold": 1,
        "time_window_seconds": 60,
        "correlation_key": None,
        "mitre_technique": "T1003.001",
        "mitre_name": "LSASS Memory",
    },
    {
        "rule_id": "RULE-LAT-001",
        "name": "Network Logon Sprawl (Lateral Movement)",
        "description": "Four or more network logons (Logon Type 3) for the same account within 5 minutes suggest lateral movement across hosts.",
        "category": "lateral_movement",
        "severity": "critical",
        "event_id": [4624],
        "conditions": {"logon_type": {"eq": "3"}},
        "correlation_type": "count",
        "threshold": 4,
        "time_window_seconds": 300,
        "correlation_key": "username",
        "mitre_technique": "T1021.002",
        "mitre_name": "SMB/Windows Admin Shares",
    },
]
